name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-license-headers:
    name: Check license headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: .github/workflows/check_license_headers.sh

  test:
    name: Build with static analysis and test
    runs-on: ${{matrix.runner}}
    strategy:
      matrix:
        runner: [ubuntu-latest, jetson-18.04]
        ros: [humble, iron, jazzy]
        ros_rmw: [rmw_fastrtps_cpp, rmw_cyclonedds_cpp]
        cc: [gcc, clang]
        api: [dds, udp]
        build_type: [Debug, Release]
    env:
      STATIC_ANALYSIS: ON
    steps:
      - uses: actions/checkout@v3
      - run: .github/workflows/test.sh ${{matrix.ros}} ${{matrix.cc}} ${{matrix.api}} ${{matrix.build_type}} ${{matrix.ros_rmw}} ${STATIC_ANALYSIS}
      - name: Docker Cleanup
        if: always()
        run: docker rm -f provizio_radar_api_ros2_test_${{matrix.ros}} ; docker rmi -f provizio_radar_api_ros2_test:${{matrix.ros}} ; docker system prune -af
